# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - java/**
  pull_request:
    branches: [ "main" ]
    paths:
      - java/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
    name: "yolks:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy: 
      # if one matrix job fails, the others do not automatically stop (default true)
      fail-fast: false
      # github-defined keyword allowing multiple parallel jobs to run (within concurrency limits)
      matrix:
        # user-defined word "tag", could be anything e.g. "version" or "dir", the values of which
        # are referred to by "${{ matrix.tag }}"
        tag:
          - jbr_21
    steps:
      - uses: actions/checkout@v4
      - name: Docker Setup QEMU
        # Install and configure QEMU to enable building images for multiple architectures
        # (e.g., linux/arm64) on GitHub-hosted amd64 runners
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        # Set up Docker Buildx for advanced multi-platform builds and BuildKit features
        uses: docker/setup-buildx-action@v3.11.1
        with:
          buildkitd-flags: --debug
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push Docker images
        # Build and push multi-architecture Docker images to the registry using Buildx
        uses: docker/build-push-action@v6.18.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/braekpo1nt/yolks:java_${{ matrix.tag }}

